### ISSUE TITLE
[tracker] Outreachy Internship: Improve UI/UX of UNICEF Inventory and redesign site around the Digital Public Goods Standard

### ISSUE THREAD

**Issue by jwflory** [unicef/inventory#124]
_This is a meta issue to track the overall Outreachy internship project for May-August 2022._

---

# Summary

There are two goals for the internship:

1. Improve UI/UX of the Inventory [Hugo](https://gohugo.io/) theme, so it is more responsive and user-friendly.
1. Redesign the existing categories to map to the [Digital Public Goods Standard](https://digitalpublicgoods.net/standard/), and work with other UNICEF colleagues and [UNICEF Innovation Fund](https://www.unicefinnovationfund.org/) start-up companies to get to know their challenges in complying with the Standard.

# Background

## Previous discussion and context

This is something we have been discussing for some time. Together with other members of the team (@acabunoc, @nathanbaleeta, @prajectory, @lacabra, and others), we started mapping what the restructure might look like in [**this Google Doc**](https://docs.google.com/document/d/1r5TxJC8byLbdfyyyG5Gh3kRCNqu84pOW82NTkVZ4pTw/edit?usp=sharing).

## Technical breakdown: Open Source Inventory V.S. Inventory theme

During the internship, you will get to know two major components of the project: the UNICEF Inventory theme and the Open Source Inventory website.

### UNICEF Inventory theme

The [UNICEF Inventory theme](https://github.com/unicef/inventory-hugo-theme) is a general-purpose theme that anyone can use to create a new knowledge-base website. The theme is made for the [Hugo](https://gohugo.io/) static site generator tool. Anyone using Hugo can import the UNICEF Inventory theme into their project and use it for building a new website.

The theme is most prominently used on the [Open Source Inventory website](https://unicef.github.io/inventory/) (explained below), but there are also other UNICEF projects and open source communities using the theme too. The UNICEF Inventory theme is a common "upstream" project for the different websites and projects using it. Changes and improvements made to the theme should benefit all downstream users.

### [Open Source Inventory website](https://unicef.github.io/inventory/)

The [UNICEF Open Source Inventory](https://unicef.github.io/inventory/) is a knowledge-base of best practices, resources, and information about working and leading Open. This is maintained as part of the Open Source Mentorship program offered by the [UNICEF Innovation Fund](https://www.unicefinnovationfund.org/). The Open Source Inventory provides mentorship and guidance to anyone seeking to adopt best practices in their journey to building an Open Source project and community. It is self-serve and can be used at various phases of building a project and community.

At UNICEF, the Open Source Inventory is an important part of how we deliver guidance and coaching to UNICEF Innovation Fund companies. The knowledge-base is used to teach best practices about working on open source projects and how to launch your own project. The overall goal is to empower others with the knowledge and background they need to be successful in their open source projects. In other words, we want to help others build successful, inclusive, and sustainable open source communities!

The Open Source Inventory website is the most well-known Hugo site using the UNICEF Inventory theme.

# Details

This section will be updated and modified as the application period comes closer. The best way to describe the general approach is in three parts:

- [x] Improve UI/UX by tackling smaller issues in the backlog.
- [x] Work with UNICEF colleagues and [Innovation Fund](https://www.unicefinnovationfund.org/) start-ups to redesign the Open Source Inventory website around the [Digital Public Goods Standard](https://digitalpublicgoods.net/standard/). This will involve UI/UX work but also working with the content hosted in the repository.
- [x] Continue making UI/UX improvements after the redesign, with a focus on bigger and more challenging improvements. A new feature may be added as a stretch goal depending on intern progress.

# Outcome

- The UNICEF Open Source Inventory is structured around the Digital Public Goods Standard and offers support material and guidance on complying with the Standard.
- The UNICEF Inventory theme is more user-friendly, responsive, and mobile-friendly.

**Comment by jwflory** [comment]
_NOTE_: If you are an Outreachy applicant and want to work on this project during the contribution phase, please start with these three issues first:

1. unicef/inventory-hugo-theme#59
2. unicef/inventory-hugo-theme#60
3. unicef/inventory-hugo-theme#61

**Comment by Abbiefied** [comment]
Hello @jwflory , I have completed the three tasks and i would like to work on this task. Thank you!

**Comment by jwflory** [comment]
@Abbiefied Hi, this issue is for the full internship. For the Outreachy contribution period, the [theme issue tracker](https://github.com/unicef/inventory-hugo-theme/issues) is the best place to look for new tasks.

I would also like to note that I [closed the project for new applicants](https://www.outreachy.org/communities/cfp/unicef/) in the Outreachy portal. It is a very competitive round and we only have one funded internship. It may be strategic to look at other communities with fewer applicants for their mentored projects. I know the [Fedora Project](https://www.outreachy.org/communities/cfp/fedora/) is one other excellent community and they are funding three interns.

**Comment by jwflory** [comment]
The scope for the DPG Standard redesign may change. As we review existing open source guidance and resources for Venture Fund companies and the DPG Alliance about the DPG Standard, there is an opportunity to consolidate our efforts to a single project. There are two other places where information about the DPG Standard is published:

* [DPG Resources](https://resources.digitalpublicgoods.net/): A prototype project from 2020 to provide more guidance and context on the DPG Standard and the interpretation of each indicator.
* [DPG Help Center](https://github.com/DPGAlliance/publicgoods-candidates/tree/main/docs/help-center): Documentation hosted by the DPG Alliance that is referenced during the review process. Most of it contains examples, pointers, and guidance about the indicators instead of checklist-style review notes, so it is compatible with other content published in the O.S. Inventory.

It would ideal for these three existing efforts to fold into one, and we can break down collaboration barriers so our teams can work more closely together.

CC: @nathanbaleeta @Idadelveloper

**Comment by jwflory** [comment]
Over the last three months, @Neha9849 heroically led the charge on completing this project! In addition to several UI/UX improvements and conducting many user interviews with Venture Fund staff and portfolio company founders & tech leads, we have a new design of the UNICEF Open Source Inventory that reflects the Digital Public Goods Standard (PR #136). I intend to make a final pass and get this merged ASAP. In the mean time, I am going to close this issue as complete.

Thanks for all your great work over the last few months @Neha9849, and all the best on your next chapters to come! 😊

**Comment by Neha9849** [comment]
Thanks Justin🙌
