### ISSUE TITLE
[CONTENT] Meta: Hugo maintainer's guide

### ISSUE THREAD

**Issue by jwflory** [unicef/inventory#30]
## Content classification

**Request for a new page, category, or section**.
The title of the new content is: "Inventory maintainer's guide"
If a page, it will belong to this category: "Meta"

## Content description

General overview of important considerations and checks for maintainers when working with this repository. Touching on governance pieces but not fully unpacking a whole governance structure on what is still, for now, mostly a one-person project.

What this guide or checklist should cover:

- [x] ~~Helpful Hugo documentation pages~~ 60d97c2d416632836d5f85161047ddcaf25762ed
- [x] ~~Issue label conventions~~ 4cb87e74796b10abcc05d56438c5421ef5bab24d
- [x] ~~Commit message conventions~~ 665ed2d94068e5b5a466941b4642819756f45f19
- [x] ~~AsciiDoc syntax cheat sheet~~ b0bc3b1cb331f8b2f53970c07c88ec0462913ed8
- [ ] CI pipeline diagram
- [x] ~~How to update git submodule for theme as a maintainer~~ 2a31b9406f784161725c32bd5e27a3975f18ec5d
- [x] ~~How development decisions are prioritized~~ 3ab71cbcb049f04e0db32b1952704e326c97366e

**Comment by jwflory** [comment]
The maintainer's guide now exists. It still needs the CI pipeline diagram before closing as complete.

https://unicef.github.io/inventory/meta/maintainers-guide/
